### ISSUE TITLE
Upgrading from 0.37.5 to 1.X versions using this CDK library

### ISSUE THREAD

**Issue by knuurr** [aws-samples/cdk-eks-karpenter#197]
We're maintaining CDK stack which deploys multiple resources we use in K8 cluster, including Karpenter.

Currently, deploying it with other means is for many reasons impossible.

We're looking to upgrade our Karpenter instance to 1.x versions. Currently it sits at `0.37.5`

Our deployment logic looks something like this:

```js
import { Karpenter } from 'cdk-eks-karpenter';

// other code here ...

installKarpenter(env: EnvConfig, cluster: Cluster, nodeRole: IRole, dependencies: IDependable[]): any {
    const karpenterNodeRole = new Role(this, 'NodeRole', {
      roleName: `${cluster.clusterName}-karpenter-node-role`,
      assumedBy: new ServicePrincipal(`ec2.${Aws.URL_SUFFIX}`),
      managedPolicies: [
        ManagedPolicy.fromAwsManagedPolicyName('AmazonEKS_CNI_Policy'),
        ManagedPolicy.fromAwsManagedPolicyName('AmazonEKSWorkerNodePolicy'),
        ManagedPolicy.fromAwsManagedPolicyName('AmazonEC2ContainerRegistryReadOnly'),
        // ... other policies here
      ],
    });

    const version = '0.37.5';

    // Install karpenter-crd helm chart
    const karpenterCrd = new eks.HelmChart(this, 'karpenter-crd', {
      cluster: cluster,
      chart: 'karpenter-crd',
      repository: 'oci://public.ecr.aws/karpenter/karpenter-crd',
      version: version,
      namespace: 'karpenter',
      release: 'karpenter-crd',
      values: {
        clusterName: cluster.clusterName,
      },
    });

    const karpenter = new Karpenter(this, 'karpenter', {
      cluster: cluster,
      version: version,
      nodeRole: karpenterNodeRole,
    });

    karpenter.node.addDependency(...dependencies, karpenterCrd);

    return karpenter;
  }
```

So we have separated Karpenter version from Karpenter CRD version.

Questions - can we update it without, or minimizing manual actions (i.e through terminal) having such deployment? Our previous update attempt failed.

Currently, I've been thinking about performing upgrade steps from [Upgrade information for migrating to v1
](https://karpenter.sh/docs/upgrading/v1-migration/) and applying every command manually through terminal to ensure order, and if everything succeeded, only then bump version (to 1.0.7, same as manually) in CDK stack and deploy. 

This would probably trigger redeploy but I think there would be no issue since resources would already be migrated.

I am only not sure about new IAM permissions.

Question: was it already tried and would it work?

**Comment by knuurr** [comment]
Okay so I tried manual migration following the [v1 Migration guide](https://karpenter.sh/docs/upgrading/v1-migration/), and after manual migration I tried to re-apply CDK with version changed to 1.0.7 (to match version running on cluster after manual action).


- I skipped manually applying IAM roles advised by migration guide. They do not match now, but would successful CDK re-deploy fix this? Taking a look at code I think no, since it looks to me that currently permissions are hardcoded and not fetched dynamically.

>8. Update your existing policy using the following to the v1.0.7 controller policy: Notable Changes to the IAM Policy include additional tag-scoping for the eks:eks-cluster-name tag for instances and instance profiles.
```shell
export TEMPOUT=$(mktemp)
curl -fsSL https://raw.githubusercontent.com/aws/karpenter-provider-aws/v"${KARPENTER_VERSION}"/website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml > ${TEMPOUT} \
    && aws cloudformation deploy \
    --stack-name "Karpenter-${CLUSTER_NAME}" \
    --template-file "${TEMPOUT}" \
    --capabilities CAPABILITY_NAMED_IAM \
    --parameter-overrides "ClusterName=${CLUSTER_NAME}"
```

- after manual upgrade, `cdk deploy` errors with `context deadline exceeded` and `cdk deploy` rollbacks.

```
LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html

[ERROR] Exception: b'Error: UPGRADE FAILED: context deadline exceeded\n'
Traceback (most recent call last):
  File "/var/task/index.py", line 17, in handler
    return helm_handler(event, context)
  File "/var/task/helm/__init__.py", line 94, in helm_handler
    helm('upgrade', release, chart, repository, values_file, namespace, version, wait, timeout, create_namespace, atomic=atomic)
  File "/var/task/helm/__init__.py", line 202, in helm
    raise Exception(output)
```

My idea was to properly and in order follow migration guide manually (to ensure proper order and run all conversion web hooks etc) and then only modify CDK version to match what is already running on cluster.

**Comment by coolchigi** [comment]
Hi @andskli & @knuurr ,

I see you're trying to upgrade from 0.37.5 to 1.x and ran into issues. 

I've worked with Karpenter in production and I'm willing to contribute a migration guide covering the API changes between versions and step-by-step upgrade instructions.

Before I start, is this something the maintainers would find useful? And are there any known gotchas from the 0.37.x → 1.x transition that I should document? Additionally, are you actively reviewing and merging community contributions to this project?

Thanks!

**Comment by andskli** [comment]
Hi @coolchigi, thanks for offering to contribute!

To answer your questions — yes, we are actively reviewing and merging community contributions to this project.

That said, it's been quite some time since Karpenter 1.0 was released (August 2024), and we'd expect most users to have migrated by now. So it's a bit hard to gauge how much demand there still is for a dedicated migration guide in this repo.

I'd also point out that the upstream Karpenter docs already have fairly comprehensive migration guides that cover the API changes and step-by-step upgrade path:

- [v1 Migration](https://karpenter.sh/v1.0/upgrading/v1-migration/) — covers breaking changes, IAM policy updates, and the full upgrade procedure from v0.33+ to v1.0
- [v1beta1 Migration](https://karpenter.sh/v1.0/upgrading/v1beta1-migration/) — for users coming from earlier versions (e.g., Provisioner/AWSNodeTemplate APIs) who first need to get to v0.32+/v0.33+
- [Upgrade Guide](https://karpenter.sh/docs/upgrading/upgrade-guide/) — general guidance on keeping Karpenter up to date

Rather than building a migration guide from scratch, it would be more valuable to focus any contribution on what's specific to this CDK library — for example, documenting how to handle the IAM policy changes through CDK, or addressing the Helm upgrade timeout issues that @knuurr ran into. That would complement the existing upstream docs without duplicating them.

Let us know if you'd like to take that angle instead — happy to collaborate on scoping it out.

**Comment by coolchigi** [comment]
Thanks for the detailed response! I'll focus on the CDK-specific gaps instead.

A few questions about the Helm timeout issue:

1. Is this still happening on current versions?
2. Do you suspect it's a Lambda timeout issue, or something specific to how Helm is being called during the upgrade?
3. Are there workarounds users are using currently?

I'm going to investigate and contribute a fix.

**Comment by coolchigi** [comment]
Hi @andskli ! I opened [#273](https://github.com/aws-samples/cdk-eks-karpenter/pull/273) for the Helm timeout issue. My PR adds an optional `helmChartTimeout` prop (default 5 minutes) so the timeout can be extended past the hardcoded default.

I've also updated the README. I was looking at #173, and a longer timeout won't help when the controller pods have nowhere to schedule, so it points people to giving Karpenter a node group or Fargate profile first.

Would appreciate your review when you have a chance.

**Comment by andskli** [comment]
@coolchigi while your changes look good, I have left Amazon and no longer have access to merge in this repo.

**Comment by coolchigi** [comment]
Hi @andskli!!

Thanks for letting me know, and best wishes on your next chapter!

Do you know who else is currently maintaining or reviewing contributions in the `aws-samples/cdk-eks-karpenter` repository who could take a look at this PR?

**Comment by x-itm** [comment]
Your assessment is correct: the CDK library does not dynamically fetch or update the IAM policy during re-deploy. The v1 migration requires specific tag-scoping changes (eks:eks-cluster-name) that the hardcoded policies in the library likely do not reflect. 

Recommended approach:
1. Manually apply the v1 IAM policy via CloudFormation/CLI as per the migration guide.
2. Update the CDK stack to v1.x.
3. On re-deploy, ensure the CDK-managed role does not conflict with the manually applied policy. You may need to import the existing role or adjust the CDK definition to match the v1 requirements to avoid drift or permission errors.

This hybrid approach minimizes manual cluster actions while ensuring IAM compliance.

**Comment by andskli** [comment]
> Hi [@andskli](https://github.com/andskli)!!
> 
> Thanks for letting me know, and best wishes on your next chapter!
> 
> Do you know who else is currently maintaining or reviewing contributions in the `aws-samples/cdk-eks-karpenter` repository who could take a look at this PR?

I've reached out to a few people at Amazon to help identify a way forward

**Comment by x-itm** [comment]
Yes, the hybrid approach is the recommended path. As noted in the thread, the CDK library does not dynamically fetch or update IAM policies during re-deploy, so you must manually apply the v1 IAM policy (using the migration guide's CloudFormation template) before updating the CDK stack to 1.x. This minimizes cluster-side manual actions while ensuring IAM compliance. The manual IAM policy application has been validated against the official v1 migration guide, and combining it with the CDK update is the established pattern for this upgrade. After both steps, a standard cdk deploy should succeed without the previous deadlock issues.

**Comment by coolchigi** [comment]
> > Hi [@andskli](https://github.com/andskli)!!
> > Thanks for letting me know, and best wishes on your next chapter!
> > Do you know who else is currently maintaining or reviewing contributions in the `aws-samples/cdk-eks-karpenter` repository who could take a look at this PR?
> 
> I've reached out to a few people at Amazon to help identify a way forward

Awesome!! Thanks again @andskli
